#!/usr/bin/python3 -u

import sys
import socket
import select
import json
from typing import List


def pad(name):
    """
    Pads the name with null bytes
    """
    return '\0{}{}'.format(name, '\0' * (107 - len(name)))


def build_socket(name: str) -> socket:
    """
    Build a socket connected to the given LAN
    """
    s = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
    s.connect(pad(name))
    return s


class Bridge(object):
    def __init__(self, bridge_id: str, lans: List[str]):
        print("Bridge " + bridge_id + " starting up\n")
        self.bridge_id = bridge_id

        self.setup_ports(lans)
        self.update_root(bridge_id, None, 0)

    def setup_ports(self, lans):
        self.ports = [build_socket(lan) for lan in lans]

    def update_root(self, root_bridge: int, root_port: int, cost):
        self.root_bridge = root_bridge
        self.root_port = root_port
        self.cost = cost

    def read_all(self):
        ready, _, _ = select.select(self.ports, [], [], 0.5)
        print(ready)

    def shutdown(self):
        for port in self.ports:
            port.close()


if __name__ == "__main__":
    BRIDGE = Bridge(sys.argv[1], sys.argv[2:])

    while True:
        BRIDGE.read_all()
